/**
 * Tutorial constants and step definitions
 * Separated to avoid circular dependencies between context and step definitions
 */

// Tutorial steps definitions
export const TUTORIAL_STEPS = {
  WELCOME: 'welcome',
  COLONY_CREATION: 'colony_creation',
  COLONY_NAMING: 'colony_naming',
  COLONY_ATTRIBUTES: 'colony_attributes',
  COLONY_CONFIRM: 'colony_confirm',
  FIRST_VIEW: 'first_view',
  UI_OVERVIEW: 'ui_overview',
  LEFT_PANEL_INTRO: 'left_panel_intro',
  COLONY_STATS: 'colony_stats',
  RESOURCE_OVERVIEW: 'resource_overview',
  ANT_ROLES_INTRO: 'ant_roles_intro',
  ASSIGN_WORKER: 'assign_worker',
  ASSIGN_SCOUT: 'assign_scout',
  CENTER_PANEL_INTRO: 'center_panel_intro',
  ZOOM_CONTROLS: 'zoom_controls',
  ANT_MOVEMENT: 'ant_movement',
  FORAGING_BASICS: 'foraging_basics',
  RESOURCE_COLLECTION: 'resource_collection',
  RIGHT_PANEL_INTRO: 'right_panel_intro',
  EVOLUTION_TREE: 'evolution_tree',
  RESOURCE_MANAGEMENT: 'resource_management',
  BUILDING_INTRO: 'building_intro',
  PLACE_STRUCTURE: 'place_structure',
  STRUCTURE_BENEFITS: 'structure_benefits',
  BATTLE_INTRO: 'battle_intro',
  DEFENSE_BASICS: 'defense_basics',
  ATTACK_TUTORIAL: 'attack_tutorial',
  TUTORIAL_COMPLETE: 'tutorial_complete'
};

// Tutorial step groups for organization
export const TUTORIAL_GROUPS = {
  SETUP: [
    TUTORIAL_STEPS.WELCOME,
    TUTORIAL_STEPS.COLONY_CREATION,
    TUTORIAL_STEPS.COLONY_NAMING,
    TUTORIAL_STEPS.COLONY_ATTRIBUTES,
    TUTORIAL_STEPS.COLONY_CONFIRM
  ],
  UI_BASICS: [
    TUTORIAL_STEPS.FIRST_VIEW,
    TUTORIAL_STEPS.UI_OVERVIEW,
    TUTORIAL_STEPS.LEFT_PANEL_INTRO,
    TUTORIAL_STEPS.CENTER_PANEL_INTRO,
    TUTORIAL_STEPS.RIGHT_PANEL_INTRO
  ],
  COLONY_MANAGEMENT: [
    TUTORIAL_STEPS.COLONY_STATS,
    TUTORIAL_STEPS.RESOURCE_OVERVIEW,
    TUTORIAL_STEPS.ANT_ROLES_INTRO,
    TUTORIAL_STEPS.ASSIGN_WORKER,
    TUTORIAL_STEPS.ASSIGN_SCOUT
  ],
  SIMULATION: [
    TUTORIAL_STEPS.ZOOM_CONTROLS,
    TUTORIAL_STEPS.ANT_MOVEMENT,
    TUTORIAL_STEPS.FORAGING_BASICS,
    TUTORIAL_STEPS.RESOURCE_COLLECTION
  ],
  ADVANCED: [
    TUTORIAL_STEPS.EVOLUTION_TREE,
    TUTORIAL_STEPS.RESOURCE_MANAGEMENT,
    TUTORIAL_STEPS.BUILDING_INTRO,
    TUTORIAL_STEPS.PLACE_STRUCTURE,
    TUTORIAL_STEPS.STRUCTURE_BENEFITS
  ],
  COMBAT: [
    TUTORIAL_STEPS.BATTLE_INTRO,
    TUTORIAL_STEPS.DEFENSE_BASICS,
    TUTORIAL_STEPS.ATTACK_TUTORIAL
  ],
  COMPLETION: [
    TUTORIAL_STEPS.TUTORIAL_COMPLETE
  ]
};

// Tutorial action types
export const TUTORIAL_ACTIONS = {
  START_TUTORIAL: 'START_TUTORIAL',
  NEXT_STEP: 'NEXT_STEP',
  PREVIOUS_STEP: 'PREVIOUS_STEP',
  GO_TO_STEP: 'GO_TO_STEP',
  COMPLETE_STEP: 'COMPLETE_STEP',
  SKIP_TUTORIAL: 'SKIP_TUTORIAL',
  COMPLETE_TUTORIAL: 'COMPLETE_TUTORIAL',
  RESET_TUTORIAL: 'RESET_TUTORIAL',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  SET_USER: 'SET_USER',
  LOAD_PROGRESS: 'LOAD_PROGRESS',
  AWARD_REWARD: 'AWARD_REWARD',
  PAUSE_TUTORIAL: 'PAUSE_TUTORIAL',
  RESUME_TUTORIAL: 'RESUME_TUTORIAL',
  MARK_FEATURE_DISCOVERED: 'MARK_FEATURE_DISCOVERED',
  TRIGGER_CONTEXTUAL_TUTORIAL: 'TRIGGER_CONTEXTUAL_TUTORIAL'
};

export default { TUTORIAL_STEPS, TUTORIAL_GROUPS, TUTORIAL_ACTIONS }; 